### ISSUE TITLE
Removing TOP results in crash when removing it from modlist.

### ISSUE THREAD

**Issue by ZeldasWetDream** [dainxt/DungeonsMod-Issue-Tracker#48]
Was told that the crash is on this mods end and that I should put a report here.

[crash-2022-02-08_01.30.11-client (1).txt](https://github.com/dainxt/DungeonsMod-Issue-Tracker/files/8027456/crash-2022-02-08_01.30.11-client.1.txt)

**Comment by dainxt** [comment]
Normally the crashes causes are always specified on the "Head" part. And from what I see from your crash report you have to install https://www.curseforge.com/minecraft/mc-mods/the-one-probe, as other mod is requiring this mod... Let me know if there is any update...

**Comment by ZeldasWetDream** [comment]
When its installed there is no problem but upon removing I get the crash. I filled out a report on the TOP github but was told its a problem on this end.

**Comment by dainxt** [comment]
Probably fixed in 1.4.62

**Comment by ZeldasWetDream** [comment]
When its uploaded I will test it out.

**Comment by ZeldasWetDream** [comment]
Whatever the problem is I don't think it is on this end cause the problem still persist. Ima close this issue and do some more debugging on my end.
